name: success_clinic
description: "Este é um aplicativo Flutter para gerenciamento de uma clínica médica, com foco em controle de usuários, médicos e medicações. O sistema permite cadastro e autenticação de usuários, gerenciamento de profissionais de saúde, registro e acompanhamento de medicações, além de oferecer uma interface intuitiva para navegação e administração das funcionalidades da clínica."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

#-------------- ./ PACKAGES START --------------#
# This section defines the packages that the Flutter application depends on.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  youtube_explode_dart: ^2.4.2
  flutter_inappwebview: ^6.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  get_it: ^8.0.3

#--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS -----------------# 
  assets:
    - assets/
    - assets\fonts
    - assets\icons
    - assets\images
    - assets\images\doctors_images
    - assets\videos
    - assets\audio
    - assets\logos
  #--------------- LOCAL ASSETS END ---------------#

  #----------------- LOCAL FONTS -----------------#
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
  #--------------- LOCAL FONTS END ---------------#